NUM_GPUS: 4

hyperparameters:
  TRAIN_BATCH_SIZE: 16
  VALID_BATCH_SIZE: 16
  MAX_EPOCHS: 1
  LEARNING_RATE: 0.0001
  SEED: 42
  MAX_INPUT_LEN: 512
  MAX_OUTPUT_LEN: 512
  NUM_BEAMS: 2
  REPETITION_PENALTY: 2.5
  LENGTH_PENALTY: 1.0
